export const CATEGORIES = [
  {
    id: 'majstori',
    label: 'Majstori',
    emoji: '🔧',
    description: 'Vodoinstalateri, električari, serviseri i drugi stručni majstori',
    color: 'from-blue-500 to-cyan-500',
    borderColor: 'border-blue-500/40',
    bgColor: 'bg-blue-500/10',
    textColor: 'text-blue-300',
    subcategories: [
      { id: 'vodoinstalater',        label: 'Vodoinstalater',        emoji: '💧' },
      { id: 'elektricar',            label: 'Električar',            emoji: '⚡' },
      { id: 'serviser-bele-tehnike', label: 'Serviser bele tehnike', emoji: '🧺' },
      { id: 'serviser-klima',        label: 'Serviser klima uređaja',emoji: '❄️' },
      { id: 'grejanje-kotlovi',      label: 'Grejanje / kotlovi',    emoji: '🔥' },
      { id: 'bravar',                label: 'Bravar',                emoji: '🔑' },
    ],
  },
  {
    id: 'kucne-usluge',
    label: 'Kućne usluge',
    emoji: '🏠',
    description: 'Čišćenje stanova, pranje prozora, generalno i dubinsko čišćenje',
    color: 'from-green-500 to-emerald-500',
    borderColor: 'border-green-500/40',
    bgColor: 'bg-green-500/10',
    textColor: 'text-green-300',
    subcategories: [
      { id: 'ciscenje-stanova',           label: 'Čišćenje stanova',           emoji: '🧹' },
      { id: 'generalno-ciscenje',         label: 'Generalno čišćenje',         emoji: '🫧' },
      { id: 'peglanje',                   label: 'Peglanje',                   emoji: '👔' },
      { id: 'pranje-prozora',             label: 'Pranje prozora',             emoji: '🪟' },
      { id: 'dubinsko-ciscenje',          label: 'Dubinsko čišćenje',          emoji: '🧽' },
      { id: 'ciscenje-nakon-renoviranja', label: 'Čišćenje nakon renoviranja', emoji: '🏗️' },
      { id: 'odrzavanje-doma',            label: 'Održavanje doma',            emoji: '🏡' },
    ],
  },
  {
    id: 'namestaj-montaza',
    label: 'Nameštaj i montaža',
    emoji: '🪑',
    description: 'Sklapanje i montaža nameštaja, IKEA, popravke i nameštaj po meri',
    color: 'from-yellow-500 to-orange-400',
    borderColor: 'border-yellow-500/40',
    bgColor: 'bg-yellow-500/10',
    textColor: 'text-yellow-300',
    subcategories: [
      { id: 'montaza-namestaja',  label: 'Montaža nameštaja',        emoji: '🪑' },
      { id: 'ikea-namestaj',      label: 'Sklapanje IKEA nameštaja', emoji: '📦' },
      { id: 'popravka-namestaja', label: 'Popravka nameštaja',       emoji: '🪚' },
      { id: 'namestaj-po-meri',   label: 'Nameštaj po meri (stolar)',emoji: '🪵' },
    ],
  },
  {
    id: 'zavrsni-radovi',
    label: 'Završni radovi',
    emoji: '🎨',
    description: 'Molerski radovi, keramika, gips, podovi, fasade i izolacije',
    color: 'from-purple-500 to-pink-500',
    borderColor: 'border-purple-500/40',
    bgColor: 'bg-purple-500/10',
    textColor: 'text-purple-300',
    subcategories: [
      { id: 'moler',            label: 'Moler',                   emoji: '🖌️' },
      { id: 'keramicar',        label: 'Keramičar',               emoji: '🧱' },
      { id: 'gipsar-knauf',     label: 'Gipsar / knauf',          emoji: '🏗️' },
      { id: 'podovi',           label: 'Podovi (parket, laminat)', emoji: '🪵' },
      { id: 'fasada-izolacija', label: 'Fasada / izolacija',      emoji: '🏠' },
    ],
  },
  {
    id: 'dvoriste',
    label: 'Dvorište i spoljašnji radovi',
    emoji: '🌿',
    description: 'Košenje trave, orezivanje drveća, čišćenje i sezonski radovi',
    color: 'from-lime-500 to-green-600',
    borderColor: 'border-lime-500/40',
    bgColor: 'bg-lime-500/10',
    textColor: 'text-lime-300',
    subcategories: [
      { id: 'odrzavanje-dvorista', label: 'Održavanje dvorišta', emoji: '🌱' },
      { id: 'kosenje-trave',       label: 'Košenje trave',       emoji: '🌿' },
      { id: 'orezivanje-drveca',   label: 'Orezivanje drveća',   emoji: '🌳' },
      { id: 'ciscenje-dvorista',   label: 'Čišćenje dvorišta',   emoji: '🍂' },
      { id: 'sezonski-radovi',     label: 'Sezonski radovi',     emoji: '☃️' },
    ],
  },
  {
    id: 'transport-selidbe',
    label: 'Transport i selidbe',
    emoji: '🚚',
    description: 'Selidbe, kombi prevoz, odvoz šuta i starog nameštaja',
    color: 'from-orange-500 to-red-500',
    borderColor: 'border-orange-500/40',
    bgColor: 'bg-orange-500/10',
    textColor: 'text-orange-300',
    subcategories: [
      { id: 'selidbe',         label: 'Selidbe',                 emoji: '📦' },
      { id: 'kombi-prevoz',    label: 'Kombi prevoz',            emoji: '🚐' },
      { id: 'odvoz-suta',      label: 'Odvoz šuta',              emoji: '🗑️' },
      { id: 'odvoz-namestaja', label: 'Odvoz starog nameštaja',  emoji: '🛋️' },
      { id: 'lokalna-dostava', label: 'Lokalna dostava',         emoji: '🛵' },
    ],
  },
  {
    id: 'sitne-popravke',
    label: 'Sitne popravke',
    emoji: '🧰',
    description: 'Bušenje, montaža polica, zamena sijalica, ugradnja TV-a i slično',
    color: 'from-slate-500 to-gray-500',
    borderColor: 'border-slate-500/40',
    bgColor: 'bg-slate-500/10',
    textColor: 'text-slate-300',
    subcategories: [
      { id: 'busenje-zidova',  label: 'Bušenje zidova',  emoji: '🔩' },
      { id: 'montaza-polica',  label: 'Montaža polica',  emoji: '📚' },
      { id: 'sitne-popravke',  label: 'Sitne popravke',  emoji: '🔧' },
      { id: 'zamena-sijalica', label: 'Zamena sijalica', emoji: '💡' },
      { id: 'montaza-tv',      label: 'Montaža TV-a',    emoji: '📺' },
    ],
  },
  {
    id: 'it-podrska',
    label: 'Tehnička podrška i IT',
    emoji: '💻',
    description: 'Popravka računara, instalacija softvera, internet i smart uređaji',
    color: 'from-indigo-500 to-blue-600',
    borderColor: 'border-indigo-500/40',
    bgColor: 'bg-indigo-500/10',
    textColor: 'text-indigo-300',
    subcategories: [
      { id: 'popravka-racunara',    label: 'Popravka računara',    emoji: '🖥️' },
      { id: 'instalacija-softvera', label: 'Instalacija softvera', emoji: '💿' },
      { id: 'internet-mreze',       label: 'Internet i mreže',     emoji: '📡' },
      { id: 'tv-smart-uredjaji',    label: 'TV / smart uređaji',   emoji: '📱' },
    ],
  },
];
